### ISSUE TITLE
TLM IDを0から振り直す

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#147]
## 詳細
[ここ](https://github.com/ut-issl/c2a-aobc/pull/137#discussion_r1275838738)での議論の通り、MOBC側の修正により、TLM IDを0から振り直せるようになった。

## close条件
- [x] TLM IDを0から振り直したら

## 備考
NA

**Comment by seki-hiro** [comment]
@200km @chutaro 
ID振り直しの方針をご相談したいです。既存は、`0x90~0xa1`が各OBC共通のもの、`0xb0`以降がAOBC固有のものになっているようです。各OBC共通のものは`0x00~`、AOBC固有のものは`0x20~`に前倒しするという方針で良いでしょうか？

既存のopsファイルのID書き換えが煩雑にならないよう、基本的に順番は変えずにIDをずらしたいと思います。

**Comment by 200km** [comment]
僕はそれで良いと思いますがCDHの意見が重要だと思うので、@chutaro くんと議論して決めてください。

**Comment by chutaro** [comment]
CDHとしてもそれで大丈夫です．

**Comment by seki-hiro** [comment]
では今夜作業進めます。
