### ISSUE TITLE
ボーレート変更コマンドに関するバグ修正

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/c2a-aobc#155]

**Comment by t-hosonuma** [comment]
[こちらのPR](https://github.com/ut-issl/c2a-aobc/pull/251)がMergeされたことに伴い，closeできると思います．

**Comment by 200km** [comment]
ご自身でCLOSEしてくださって良いですし、`Development`でPRと連携させていれば、PRマージ時に自動でCLOSEされるので、その機能をご活用ください。
