### ISSUE TITLE
エラーフラグFDIR実装検討

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/c2a-aobc#156]

**Comment by t-hosonuma** [comment]
@seki-hiro @200km   
済みません，このissue，もう少し具体的にはどういう意図で，何をもって完了にできる想定だったか覚えていますでしょうか…？

**Comment by 200km** [comment]
元々は、下記PRから抜き出されたものなので、GPS関連のものです。
https://github.com/ut-issl/c2a-aobc/issues/19

GPS-Rが測位できていない時などにエラーフラグが立つとしたら、それを検知してFDIRを組むというものだと思います。エラーフラグがない場合は可視衛星数が少ないなどで判断しても良いかと思います。

**Comment by 200km** [comment]
「検討」なので、そもそも実装する必要があるか、Dまではするが、IRは必要ないかなどの結論が出れば完了だと思います。

**Comment by t-hosonuma** [comment]
了解です，有難うございます

**Comment by t-hosonuma** [comment]
上の話を鑑みるに，このタスクはGPS-Rが測位できていないときのFDIRの対処方針を定めるという話かと解釈しました．  
下記方針で良いのではないかと思っています．
1）機器単体の操作だけでは基本，リカバリは困難なので，機上でのRは実施しない
2）一方で，地上から状況を把握できる余地を残すため，Dについては追加する．（イベントハンドラに登録する）

**Comment by 200km** [comment]
新しいissueを切り出したので、これでCLOSEする

https://github.com/ut-issl/c2a-aobc/issues/264
