### ISSUE TITLE
MTQ関連コードのリファクタリング

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#16]
## 概要
MTQ関連コードのリファクタリング

## 詳細
大きく次の2つが関係する
- MTQ/磁気センサ排他制御の管理方法
- MTQドライバ周りのバグ調査
  - [参考](https://gitlab.com/ut_issl/c2a/c2a_issl6u_aobc/-/issues/264)
- MTQドライバでstep_time_msが負にならないことを保証するようにする

## close条件
リファクタできたら

## 備考
NA

## 注意
NA

**Comment by suzuki-toshihir0** [comment]
@200km @t-hosonuma 

遅くなってしまいすみません。磁気制御全体のリファクタリングの件について、方針をまとめたのでこの方針で行けそうか確認したいです。

- 本質的な問題は、PWMタイマと消磁タイマが別のアプリに跨って存在していること。消磁時間はHW依存の量になるので、PWMタイマーと合わせてドライバで一括管理できるようにしたい。
  - 具体的な実装のイメージは以下のとおりになる：
  - MTQドライバ全体の「MTQ出力タイマー」のようなものを一つだけ持っておき、このタイマーは例えば1秒で1周するものとする。最後の100msは消磁のために予約されており、必ず出力が零になるようにドライバ内部で制御されるものとする。PWM制御は残りの900msで行われるようになる。
- MTQコントローラの役割は現状3つあり、MTQコントローラの責務がやたら大きくなってしまっているのが磁気制御全体をわかりにくくしている原因になっているように見える。
  - 3つの役割とは、以下のとおり。
    - (1) 目標出力磁気モーメントをMTQが出力すべきpwm dutyに変換し、MTQ DIに伝える 
    - (2-a) 消磁タイマーを管理する
    - (2-b) 消磁タイマーの値も考慮しつつ、MTQの出力状態を監視し、MTQの出力状態がオン or オフ or 消磁中であることをAOCS Managerに教える
  - 消磁タイマーをMTQドライバの中に入れ込むことで、MTQコントローラの役割を以下の2個に単純化することができる。
    - (1) 目標出力磁気モーメントをMTQが出力すべきpwm dutyに変換し、MTQ DIに伝える
    - (2) MTQの出力状態を監視し、MTQの出力状態がオン or オフであることをAOCS Managerに伝える
  - さらにいえば、MTQコントローラーと呼べる機能は (1) であり、(2) の機能はどちらかといえば「MTQオブザーバー」と言うべき機能である。アプリの責務を分割できるのであれば分割したほうが見通しがよくなると思っているので、この際 (1) と (2) は別アプリに分割したい。
- また、MTQコントローラアプリで使っている、AOCSマネージャ内部のMTQ/磁気センサ排他制御タイミング管理状態フラグ（ `AOCS_MANAGER_MAG_EXCLUSIVE_STATE` ）は実質的にはアンローディングでMTQ制御を入れるかどうかの判断にしか使われていない。その意味では「MTQ/磁気センサ排他制御タイミング管理状態フラグ」という命名は現状実体に即しているとはいえず、「アンローディング中のMTQ出力を許可するフラグ」のような名前にし、AOCSマネージャやMTQコントローラアプリからは使わないようにし、アンローディングアプリに閉じるようにしたい。こうすることで、MTQコントローラアプリがもう少し単純化される。

**Comment by 200km** [comment]
これまで何度か議論してきたことも踏まえて、気になっていることを書きます。

### 解決したい問題の本質
- MTQコントローラが適切に呼ばれているときには問題ないが、そうでないタスクリストで問題が発生し得る
- 修正前までのinitialモードや、bdotモードがそれに当たる
    - BdotはMTQコントローラを使っているが、排他制御を自分のアプリ内で勝手にやっているので、他と整合が取れていない
- それとは別にMTQ内部のコードが読みづらいので修正したいという話もある
    - PWM制御と排他制御の関係が曖昧など
- 解決したいことのまとめ
    - MTQの制御方式、磁気センサとの排他制御は全ての場所で統一のものを使いたい
    - MTQ関連内部コードを読みやすく、使いやすくする

また、これらの議論の時に使う言葉や概念をを統一したいのでそこも整理します。

### 消磁と排他制御の言葉の整理
- 消磁(時間): MTQ OFFにしたはずなのに磁気センサ的にはまだMTQがONになっているようなノイズが乗っていることがあるので、OFF後一定時間経ってから観測を開始するべきで、その時間のこと
- 排他制御: MTQ ONのときは磁気センサ観測量に大きなノイズが入るからMTQ ONと観測が排他になるように交通整理しましょう ということ。

### MTQ ON/OFFの定義
- PWMの中でduty90%の時に10%分だけOFFになることもOFFというのか、それともduty0%で全く出力しない状態をOFFというのか整理して議論したい
- 排他制御も、10%分だけOFFのときに磁気センサ観測をするのか、duty=0の時だけ観測するのかで複雑度が分かれている
    - 前者の方が複雑だが高頻度に観測できそう
        - 今の実装は基本はこれを目指していそうだし、修正案もこっちよりな気がする
    - 後者はシンプルそうだが、観測頻度が下がる可能性がある
        - Bdotは後者になっている気がする（PWMよりも長い周期で独自に出力を止めている）
- どっちで進めるべきなの？磁気センサの観測って実際どれくらいの頻度必要なの？

これらを踏まえて、僕の考えを書きます。ただ、特に絶対こうすべきということでなく、あくまでこういう考え方もあるよねという程度です。

### MTQ DriverがPWMを持つべきか
- 他のコンポドライバと持つべき機能のレイヤーを合わせるなら、MTQドライバがやることはGPIOのON/OFFだけであるべきで、PWMを持つ必要はない
- PWM機能はアプリの方で持つべきで、mtq_pwm_controllerなどのアプリがあるのが自然な気がする
- GPIOはいつでも操作できるので、ドライバインスタンスというのも無くなる可能性もある

### 消磁とPWMの関係
- PWMはMTQだけへの操作であり、消磁はMTQと磁気センサの関係でくるもの。
- 前者はMTQだけなのでmtq_driverでという今の方針もわからなくもないが、前述の通り他コンポとレイヤーを合わせるなら、PWMはドライバから分けた方が良さそう
- 後者はMTQだけでは決まらないので、それがMTQドライバの中に入るのは変な気がする。
- 消磁時間100msというのも実際の消磁時間計測から考えると過剰だということだったと思うし、スパイクフィルタを入れているなら、そもそも消磁を待つ必要はないかもしれない

### MTQと磁気センサの排他制御
- MTQ ONの時は磁気センサ値を使わないというのは、複数コンポの関係をまとめる高いレイヤーでやるべきことなのでMTQドライバが担うのは変な気もする。
- タスクリストでいつ磁気センサが呼ばれるのかなども含めて全体管理するべきことな気がする

### MTQコントローラとオブザーバを分けるか？
-コントローラを広義のものと捉えるかという命名の問題なだけな気がする
    - 広義の制御器は観測器も含んでフィードバックしたりより上位の人に状況を伝えるものとも捉えることができる
- オブザーバがコントローラを信じずに、電流系の情報などから第三者的にMTQの出力を監視するなら別でも良いと思う
- 今回はそうでないと思うので、分けなくて良い気もする

### MTQコントローラの責務が重すぎる？
- PWM制御と排他制御が深く関連しているにもかかわらず、責任が分担されているから読みづらい・バグが出やすいというのが元々出ていたことなので、そういう意味では責任の所在を一つにまとめるという責務を大きくする方向が良いようにも思える
- 逆に修正案はMTQ driverの責務が重すぎる気もしている
- 結局はうまくやりましょうということしか言えない気がするが、なんとなくdriverをシンプルにしてcontroller側に機能を持たせていくというのが良い気がしている
- ただ、（消磁ではなく）排他制御に関しては磁気センサとの関係が重要なのでMTQだけで何かするのも変だと思う。EXCLUSIVEフラグがうまく使われていないのは上位レイヤー側の設計がうまくできていないからだと思うので、名前を変える方針ではなく、上位レイヤー側もしっかり考えるというのもありえる
- 要するにMTQコントローラを単純化するのが大きな目的ではなく、全体として単純化するのが重要だということです。

**Comment by suzuki-toshihir0** [comment]
ありがとうございます。

- "解決したい問題の本質"、"消磁と排他制御の言葉の整理" についてはおおむね了解です。
  - 「消磁」については微妙に理解できていなくて、MTQの通電を切った後もコイルの時定数があるので電流がすぐにゼロにならないことによって磁気モーメントが残るものであると思っていたのですが、そうではないですか（理解間違っていたらすみません）？もしそうであるなら、消磁はMTQだけで決まるのではないかなと思っていて、それがさきほどの提案（消磁時間もMTQドライバに入れてしまう）につながっています。
- "MTQ ON/OFFの定義" については、どちらで考えるのかは合意を取りたいですね。現状僕は後者寄りです。前者はMTQのPWMのパルス幅が長いという前提に乗っかっていて、本来もっと高速にPWM制御できていれば前者のような考え方は生じないだろうという考えがあります（HWが改修されてもっとパルス幅の小さいPWM制御ができるようになったら前者の考え方に結局は寄るだろう、と思っています）。ただ、結局磁気センサの観測をどれくらいの周期でやりたいか次第だとは思っていて、それが後者の考えで満たせないなら前者で進めるしかないかな、という気持ちでいます。

### MTQ DriverがPWMを持つべきか
- 「MTQドライバがやることはGPIOのON/OFFだけであるべきで、PWMを持つ必要はない」については、そういう気もしますね。
- 一方で、PWM機能がどこで提供されるべきかについては、 `mtq_pwm_controller` 的なもの以外にも、IFWrapperでやるという考えもある気もしますが、どう思いますか？（MTQ controllerにPWM機能と排他制御機能をまとめて入れ込むならこの議論は必要ない気もしますが）

### 消磁とPWMの関係
- これは上記の「消磁」の定義次第かなと思います。

### MTQと磁気センサの排他制御、MTQコントローラとオブザーバを分けるか？
- さきほどのコメントだと消磁と排他制御が混ざってしまっていたので再度整理します。排他制御をドライバでやりたいというわけではなく、排他制御は（より高いレイヤの）MTQコントローラでやりたいと思っています。
- 「コントローラを広義のものと捉えるかという命名の問題なだけな気がする」、については同意です。コントローラにオブザーバ的機能が入っていると全体として僕としては曖昧に見えてしまう、という話になってしまう気がしますが。。。

### MTQコントローラの責務が重すぎる？
- 整理している感じだと、MTQドライバに機能を寄せるのは微妙かもしれないですね。機能を寄せていくならcontroller側のほうが良さそうであるというところはある程度納得しました。
- 上位レイヤーの設計についてはもう少し整理して考える必要がありそうです。

**Comment by 200km** [comment]
> 「消磁」については微妙に理解できていなくて、MTQの通電を切った後もコイルの時定数があるので電流がすぐにゼロにならないことによって磁気モーメントが残るものであると思っていたのですが、そうではないですか

微妙に認識が違うと思います。 
- アクチュエータの出力遅れ
  - 鈴木くんが気にしているのはこちらのようですが、これはRWも含めて全てのものにあります
  - S2E上はRWだけこれ（指令遅れ）を模擬していてMTQは特に模擬はしていません
  - これは誤差と扱えばよいと今は考えていて、MTQだけ特別に扱って「長く出力が出る分を考慮してわざと短く出力する」などの処理をやっている認識ではありません

- センサの検出遅れも含めた検知の遅れ
  - 私が気にしていることや、元々の実装の中で気にされてきたのはこちらのことだと思っています
  - MTQをOFFにしているのに磁気センサにMTQ由来の大きなオフセットノイズが乗っているというものです
  - このノイズが乗る原因としては、次のようなものがあります
    - MTQの出力遅れ
    - 磁気センサの反応遅れ（LPFなどの効果も含める）
  - これも`RW-ジャイロセンサ`なども含めて様々なアクチュエータとコンポの関係性の中であり得ることですが、その中でも特に`MTQ-磁気センサ`の関係が影響が大きいことがわかっているので、MTQ-磁気センサラインについては特に気をつけて実装しているわけです。

この件で重要なのは、そもそも `MTQ ONの時には磁気センサに大きなバイアスノイズが乗ってしまうので排他制御しないといけない` というのがあり、その上で`MTQ OFFの瞬間にまだ磁気センサにはバイアスノイズが乗っている可能性があるからちょっと時間マージンを持たせましょう`ということで、その時間マージンのことを`消磁時間`と読んでいるわけです。

**Comment by 200km** [comment]
> "MTQ ON/OFFの定義" については、どちらで考えるのかは合意を取りたいですね。

ここは丁寧に議論するのが良いと思います。私も可能なら後者でやるのが良いと思っています。


> IFWrapperでやるという考えもある気もしますが

HW PWMを使うならそれに指令を出す関数をまとめたIfWrapperが作られるのはわかりますが、ここでやっているのはS/W PWMでIfWrapperで定義されているGPIOを操作するということです。そうなると`IfWrapper PWMでIfWrapper GPIOを操作する`という若干変な構成になる気がしています。  
とはいえここは特に強い意見ではないです。


> コントローラにオブザーバ的機能が入っていると全体として僕としては曖昧に見えてしまう

先に書いたことに近いですが、僕の中での基準は次のような感じです。
- コントローラが認識できないものをオブザーバーが観測するのであれば、分ける
  - 例１: 電流センサレベルでOFFになったことを確定する
  - 例２：　コントローラーはPWM dutyを設定するだけで、実際いつON/OFFしているかはわからない可能性もある。その部分でPWM制御しているアプリや関数でOFF指令を出している時間を検知しにいく（MTQ ON/OFFの定義をどうするかにも関わる）
    - ただ、この場合はオブザーバーアプリを作るよりも、PWMアプリがOFFの時を教えるフラグを立てれば良いだけな気もする
 
- コントローラが認識できているのであれば、オブザーバーを挟んでも無駄に一段増えるだけなので分けなくて良い
  - 例1: MTQ ON/OFFの定義を後者にして、コントローラーがPWM duty=0にしたかどうかを磁気センサ側に伝えたい場合は、コントローラー側が完全にON/OFFを認識できているのでOFFかどうかのフラグを立てればよく、そのフラグを磁気センサ側などが直接読めば良い。
  - 例2: コントローラがPWM制御も含むのならコントローラ側でPWMのOFF期間も完全に把握できるので、OFFかどうかのフラグを立てればよく、そのフラグを磁気センサ側などが直接読めば良い。

**Comment by suzuki-toshihir0** [comment]
### 消磁の言葉の定義について

- MTQの出力残りだけでなく、LPFを含めた磁気センサの反応遅れも合わさって決まるということですね。理解しました。それでは、この後の議論ではそうであるという前提で進めます。

### MTQ ON/OFFの定義について

- いまPWMのパルス幅を長く取らなければいけない状況のなかで、PWM制御中にOFFになったタイミングで磁気センサの観測を挟みたいか次第でしょうか... こちらは細沼さんの意見も聞きたいと思うのですが、いかがでしょうか？ @t-hosonuma 

### IfWrapperで扱うかどうかについて

- HW PWMとSW PWMを分けて考えるなら、確かにSW PWMをアプリケーションとして解釈するのも自然な気がします。
- IfWrapper PWMでIfWrapper GPIOを操作するのは、構成としては若干歪かもしれませんが、それ自体はそこまで気にならないようにも思います。MTQコントローラの仕様をどうするのかと合わせて、全体のなかで決められればと思います。

### コントローラとオブザーバを分けるかどうか

- こちらについては概ね理解できてきました。基準については納得できそうです。

### MTQコントローラアプリのなかで排他制御をやるべきか？

- 上のとおり、消磁が「MTQの出力残りだけでなく、LPFを含めた磁気センサの反応遅れも合わさって決まる」であるので、それに伴う排他制御も「MTQの都合と磁気センサの都合との両方によってそれらの動作を決めるもの」になると理解しました。そうであるならば、さきのコメントで保留した「上位レイヤーの設計についてはもう少し整理して考える必要がありそう」については、MTQコントローラのなかで排他制御を扱うよりは、MTQと磁気センサ両方の上位にあたる排他制御ハンドラみたいなアプリを作って扱うのが自然な気もしてきました。

**Comment by t-hosonuma** [comment]
@suzuki-toshihir0   
遅くなってしまって済みません．  
  
> いまPWMのパルス幅を長く取らなければいけない状況のなかで、PWM制御中にOFFになったタイミングで磁気センサの観測を挟みたいか次第でしょうか...  
  
On/Offの定義の話に戻ってしまいますが，ここでいうOFFは，duty0%状態の間（PWM1cycleと次cycleの間）という話ではなく，PWM1cylce中の出力停止期間，ということですよね？  
現状の実装は，たしか，磁気センサの観測がPWM1cylce中に行われることはなく，PWM1cycleと次cycleの間に挟んでいた気がするので，この記憶が正しければ，新たにPWM1cylce中に磁気センサ観測を挟みたいという積極的な要求は出てこないように思います．

**Comment by suzuki-toshihir0** [comment]
@t-hosonuma ありがとうございます、

> ここでいうOFFは，duty0%状態の間（PWM1cycleと次cycleの間）という話ではなく，PWM1cylce中の出力停止期間，ということですよね？

そのとおりです。

> 磁気センサの観測がPWM1cylce中に行われることはなく，PWM1cycleと次cycleの間に挟んでいた気がするので，この記憶が正しければ，新たにPWM1cylce中に磁気センサ観測を挟みたいという積極的な要求は出てこないように思います．

ちょっとこちら再確認しますね。制御の都合上磁気センサの観測頻度を1Hzより大きくしたいという特別な要求が別になければ、PWM1サイクル中に時期センサ観測をしたいということにはならないと思うので、それでよければその方向で行きたいと思います。

**Comment by sksat** [comment]
別の場所で似たような議論があったので，斜め読みですがソフトウェアの設計の観点で1点コメントでしておきます

> HW PWMを使うならそれに指令を出す関数をまとめたIfWrapperが作られるのはわかりますが、ここでやっているのはS/W PWMでIfWrapperで定義されているGPIOを操作するということです。そうなるとIfWrapper PWMでIfWrapper GPIOを操作するという若干変な構成になる気がしています。

これに関してなのですが，このような構成は今あまり取られていないだけで，相互依存さえしなければ（例えば PWM の IfWrapper 実装が GPIO の IfWrapper 実装に依存していて，かつ，その上で GPIO の IfWrapper 実装が PWM の IfWrapper 実装に依存してしまっている，というような状況にならなければ）妥当な設計だと思います．
もっと大きな OS でも，GPIO を操作するデバイスドライバと，それを使ってソフトウェア的に UART を喋るデバイスドライバ，などは存在していがちですが，内部でそれぞれの依存関係が発生してこそいるものの，どちらも同じデバイスドライバというレイヤで実装されています（デバイスドライバ，というレイヤー構造の中に，実装が1段のものと多段のものがある，というイメージ）．

あと，↑では "IfWrapper 実装" という言葉を使って区別しましたが，IfWrapper のインターフェースを提供する部分（ヘッダファイル）とその実装（"IfWrapper 実装"）はある程度区別して考えた方がよいです．今回の場合だと，インターフェース部分（`pwm.h` みたいなやつ）が別の IfWrapper ないし IfWrapper 実装に依存しているとちょっと変（そして，今回の場合はハードウェア実装の PWM とソフトウェア実装の PWM を想定していて，必ずしも PWM が GPIO に依存するわけではないので，おかしい，となる）ですが，インターフェースはあくまで個別に独立して存在している上で，IfWrapper 実装があくまでその内部で別の IfWrapper 実装に依存している（ことがある），という設計はそんなにおかしくない，という話ですね．
