### ISSUE TITLE
SagittaのPOWERテレメがおかしい

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/c2a-aobc#160]
## 詳細
SagittaのPOWERテレメがおかしい
すべて-1で表示される

## close条件
解決したら

## 備考
https://github.com/ut-issl/c2a-aobc/pull/137#issue-1817700281

**Comment by seki-hiro** [comment]
メーカー側で確認中のため、継続対応します。

**Comment by seki-hiro** [comment]
EM固有の問題とのこと。FMで試験し、問題なければcloseする。

**Comment by conjikidow** [comment]
FMで試験した結果，EMのように `-1` とはならなかったが，全て `0` となった。
![スクリーンショット 2024-02-26 101938](https://github.com/ut-issl/c2a-aobc/assets/103401287/b46d301c-567e-4c88-a8bd-1a689da6fa95)

**Comment by conjikidow** [comment]
FMで試験した結果，問題なくテレメが得られた。
![スクリーンショット 2024-02-26 102753](https://github.com/ut-issl/c2a-aobc/assets/103401287/a197c9a3-60ec-4e7d-822e-49c475d562f1)

@seki-hiro 一応close前に確認お願いできますか？

**Comment by seki-hiro** [comment]
確認ありがとう！

CMVPixだけ、他と比較して電流と電圧が入れ替わってそうですが、テレメ周りのコード見ても特段問題なさそうなので、そういうものっぽいですね。

-1以外の値が入ることは確認できたのと、1.8, 2.5, 2.1, 3.3V出るべきラインは出ているので、closeで問題ないと思います。

**Comment by conjikidow** [comment]
確認ありがとうございます。
