### ISSUE TITLE
ユニット-ボディの座標変換実装

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#20]
## 概要
ユニット-ボディの座標変換実装

## 詳細
これまではbody座標とユニット座標が一致していたが、そうでない衛星で一括変換できるようにしたい

## close条件
実装したら

## 備考
NA

## 注意
NA

**Comment by 200km** [comment]
## 解決案
1. c2a-aobc内での`body`という言葉の定義を、`AOCSモジュール固定座標系`と言う定義と決めてしまい、それに合わせるように運用・MOBC側で全てを調整するようにする。コードは変えない。
2. c2a-aobc内での`body`という言葉の定義を、`衛星機体固定座標系`と言う定義と決めてしまい、テレコマI/F部で`AOCSモジュール-衛星座標変換`を毎度はさむようにコードを変える。制御部分などでつかうQuaternionは今のまま。一括で変えるのは大変だし、バグも入りそう。

@seki-hiro @suzuki-toshihir0 どちらが良いかなどコメントもらえると嬉しいです。

**Comment by seki-hiro** [comment]
1. の方がいいと思いました。

aobcはあくまでsub obcで、c2a-aobc側で毎回`AOCSモジュール-衛星座標変換`を考慮する必要はないと考えます。`コンポ/アクチュエータ固定座標系-AOCSモジュール固定座標系変換`をAOCSモジュール側で行うのと同様に、`AOCSモジュール-衛星座標変換`は衛星側（=OBC or 運用）で行うのが自然に思います。

衛星の慣性モーメント・RMM等、`衛星機体固定座標系`から`AOCSモジュール固定座標系`に変換して反映する必要があるものも、各プロジェクトで変換作業を行い、c2a-aobcに書き込むのは`AOCSモジュール固定座標系`の値に統一するのが良さそうです。

**Comment by 200km** [comment]
@seki-hiro コメントありがとうございます。1の場合、全ての変数名などを`body`から`aocs`などにrenameしたほうが良いと思いますか？  
それともとりあえずはreadmeなどに書いておけばいいですかね？

@suzuki-toshihir0 多くの意見が欲しいので、コメントよろしくお願いします。

**Comment by seki-hiro** [comment]
renameまでは必要ないかなと思いました。readmeへの記述はあると良さそうです。

**Comment by 200km** [comment]
とりあえず`readme`は修正した。

**Comment by suzuki-toshihir0** [comment]
だいぶコメントが遅くなってしまいすみません．

僕も1がよいと思っています（理由も関根くんが挙げてもらっているものと同様です）．衛星全体の慣性モーメントやRMMをAOCSユニットの座標系で考えなければならないのは若干の気持ち悪さはありますね．仕方ない気もしますが．．．

**Comment by 200km** [comment]
ありがとうございます。  
1で良い場合、当面の作業は必要な意ですね。

このissueをCLOSEするか、遠い将来2番の方をやることを想定して、issueを残してMilestoneを変えるかどちらにしたいのですが、どちらが良いでしょう？

**Comment by suzuki-toshihir0** [comment]
今の結論だと将来2をやるというわけではなく1のまま行くという方針になりそうなので，そうであれば閉じて良いと思います．

**Comment by seki-hiro** [comment]
1になったと思うので、僕もcloseでいいと思います。

**Comment by 200km** [comment]
ではCLOSEしようと思います。
