### ISSUE TITLE
Sagitta関連のリファクタ

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#21]
## 概要
Sagitta関連のリファクタ

## 詳細

- [ ] #176
　　- ローカルでは実装済み
- [x] キャスト不具合修正
- [x] バッファサイズの調整
- [x] bootしたかどうかのフラグ管理方法の見直し
- [x] `the centroids values`と`the histogram data`のテレメを下ろす
- [ ] エラーフラグFDIRの実装検討

## close条件
リファクタしたら

## 備考
NA

## 注意
NA

**Comment by seki-hiro** [comment]
キャスト不具合調整は、 #115 で対応。
バッファサイズ調整は、 #161 #170 で対応完了。
bootフラグの見直しは、 #115 で対応完了。
テレメ追加は #170 で対応完了。

**Comment by seki-hiro** [comment]
メモリ書き込みコマンドの追加は、直近で使用予定がないため、単体のissueとして切り出す。 https://github.com/ut-issl/c2a-aobc/issues/176
エラーフラグFDIRは、他のコンポーネントとの粒度を揃える必要があり、FDIR全体の見直しで対応する。 #75
