### ISSUE TITLE
BCT情報を不揮発メモリに移動させる

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#22]
## 概要
BCT(Block Command Table)情報を不揮発メモリに移動させる

## 詳細
BCT情報を不揮発メモリに移動させる
詳細はCDHと議論が必要

## close条件
不揮発メモリに移動できたら

## 備考
NA

## 注意
NA

**Comment by conjikidow** [comment]
別issueで対応するのでこちらはcloseします。

**Comment by 200km** [comment]
タスク管理のためreopenして担当者を変更した。
