### ISSUE TITLE
太陽センサ観測範囲オーバー時の処理追加

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#241]
## 詳細
太陽センサの角度が観測範囲をオーバーしているが、intensityは正常範囲内の場合もセンサ情報を弾くようにする。  
次のどちらかの実装があり得る
- エラーコードでOut of Rangeが出ている場合は値を信じない
- 角度が範囲限界である「60度-α」を超える場合は値を信じない

後者の方がエラーコードが間違っていた場合なども含めて対応できるので、後者が良いのではないかと考えている。

## close条件
上記機能を実装したら

## 備考
NA

**Comment by SeirenTDoi** [comment]
@200km 「alpha、betaとして-60度以下と60度以上は信じない」（エラーコードは確認しない）にしようと思いますがよろしいでしょうか。

**Comment by 200km** [comment]
よろしくお願いします。
