### ISSUE TITLE
EL, EHのグループ分けを再考する

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#25]
## 概要
EL, EHのグループ分けを再考する

## 詳細
ELのenable, disableを簡便にするため、コンポごとのELは`EL_GROUP_ERROR_コンポ名`でなるべく統一し、noteの`コンポ名_EL_NOTE`でそのEL内容を区別する方針であった。ただし、`EL_GROUP_ERROR_コンポ名`でまとめ過ぎてしまうと想定しない挙動が起こりうるため、再考する。

##### 現状の問題点
STIM210のCRCエラーは`group=EL_GROUP_ERROR_STIM210, local=STIM210_IDX_IN_UNIT, err_level=EL_ERROR_LEVEL_HIGH`のELに対して、電源リセット->電源OFFのEH対処を行う。一方、STIM210フィルタのエラーも同一のgroup, local, err_levelに対してEL登録されうる。フィルタエラーはすでに飛び値除去の処理が行われているため、EH対応はしないという方針であったが、共通のEL_groupを使用しているために、意図しない挙動をする可能性がある。

##### EL(group, local, level, note)のgroupを区別する理由
- noteで詳細を書きたい (localはコンポidxに使用）
  - ex.TLMエラー
- EHの対処が異なる（EH1つに対しEL(group, local, level)1つが必要）
  - CRCは基本電源リセットし続ける
  - OCは電源リセットを試し、復帰しなければ電源OFF
- EHで対処しないEL
  - ex.飛び値除去イベント
  - ex.モード遷移イベント

##### 今後のEL group方針案
- EHの対処が異なるものはELが別で必要なため、まとめない
  - CRCのEL groupは別にする
- EH対処が同一なものをまとめるかどうかは要検討
- EH対処しないものはなるべくまとめる
  - ELのenable, disableの手間を減らす

#### その他関連する調整事項
- RWのCRCはEL HIGHで登録されているが，テレメが正常に受け取れていたとしても，低頻度に発生するため，LOWで良さそう．
- 他にもELのレベルが妥当かどうかをSPHERE運用を踏まえて再考する．
- HKにEH Group情報を入れるかどうかも検討する

## close条件
- 方針が決まったら

## 備考
ローカルでの詳細議論  
https://gitlab.com/ut_issl/c2a/c2a_issl6u_aobc/-/issues/229

## 注意
NA

**Comment by conjikidow** [comment]
上記をベースに，以下の方針でいかがでしょうか。

- 前提
    - EH と EL (group, local, err_level) は 1 対 1 に対応する
    - local はコンポの index にあてる
- 方針
    - note に event の詳細情報を持たせたい場合，EL group は別にする
        - note に event の詳細を持たせる場合，err_level でしか EL を区別できないため
        - ex.) TLM エラー
    - EH 対処（対処しないことも含む）が異なる event の場合，原則 EL group は別にする
        - ex.) OC エラーと CRC エラー
        - ただし，同一/類似の event に対して err_level ごとに対処を変える（対処しないことも含む）場合は同じ EL group を用いることを許容する
            - ex.) フィルタのエラー（除去するごとに err_level=LOW で EL 登録するものの対処はしないが，一定回数連続で除去され場合は err_level=HIGH で EL 登録して EH で対処する）
    - 以上に該当しないものは EH 対処（対処しないことも含む）が同一の event ごとに EL group を極力統一する
        - ただし，個別に enable / disable したい EL については EL group を別にする

**Comment by seki-hiro** [comment]
まとめありがとうございます。方針良さそうです。

関連情報を共有しておきます。EHにおいて，event groupで EH Rule を操作する関数，コマンドが追加されているので、一番下の方針に該当するEHのactivate/inactivateはまとめてできるようになりました。
https://github.com/ut-issl/c2a-core/issues/337
https://github.com/ut-issl/c2a-core/pull/340

**Comment by conjikidow** [comment]
なるほど，情報共有ありがとうございます。

**Comment by conjikidow** [comment]
現状のEL/EHを整理しました。
方針の議論のためなので，EHの中身は一部省略しています。
[スプレッドシート](https://docs.google.com/spreadsheets/d/15ASqp4osw4gCL0uec3NZH8zWn-dyCQNCn5LGipehYN4/edit#gid=411990024) (private)

**Comment by conjikidow** [comment]
@200km @seki-hiro 
> EH と EL (group, local, err_level) は 1 対 1 に対応する

と思っていたのですが，上のスプシでもご確認いただけるように，実際にはサンセンサ関連の `EH_RULE_TLM_ERROR_NANOSSOC_D60` `EH_RULE_CHECKSUM_ERROR_NANOSSOC_D60` で1つのEHに対し複数のELが登録されていました（例えば前者は[これ](https://github.com/ut-issl/c2a-aobc/blob/develop/src/src_user/Settings/System/EventHandlerRules/event_handler_rule_tlmcmd.c#L86-L132)に該当します）。

これは想定通りの実装なのでしょうか。このような記述が可能な場合，同一のEH_RULEに対して複数のBCを設定できてしまいそうに見えます。

**Comment by seki-hiro** [comment]
STTのテレメエラー対処をどうするかを議論したいです。SPHでは、打ち上げ時は電源リセットでしたが、打ち上げ後DIリセットのみに変えています。
https://github.com/ut-issl/6u-aocs-task/pull/73#discussion_r1587173225

個人的には、STTのテレメエラーには対処したので、テレメエラーは起きにくく、電源リセット（現状のまま）でいいのではないかと考えています。

**Comment by seki-hiro** [comment]
SSのテレメエラー対処も考えたいです。
https://github.com/ut-issl/6u-aocs-task/pull/73#discussion_r1587246579

**Comment by conjikidow** [comment]
一応このissueの範囲はEL/EHのグループ分けまでなので具体的な対処までは扱わない予定でした（グループ分けが遅くなっていることは申し訳ないですが）。

**Comment by seki-hiro** [comment]
了解です。グループ分け後に具体的な対処を決めるって感じかな？

**Comment by seki-hiro** [comment]
@conjikidow 
> これは想定通りの実装なのでしょうか。このような記述が可能な場合，同一のEH_RULEに対して複数のBCを設定できてしまいそうに見えます。

OSS化の過程で書き換えられてしまったようです。
https://gitlab.com/ut_issl/c2a/c2a_issl6u_aobc/-/blob/develop/src/src_user/Settings/System/EventHandlerRules/event_handler_rule_tlmcmd.c?ref_type=heads#L83

**Comment by conjikidow** [comment]
> テレメエラーとCRCエラーはさすがに個別に扱うから、その具体的な対処は別issueに切り出すみたいな方針かな？

このつもりでした。

**Comment by conjikidow** [comment]
@seki-hiro @200km 
[スプレッドシート](https://docs.google.com/spreadsheets/d/15ASqp4osw4gCL0uec3NZH8zWn-dyCQNCn5LGipehYN4/edit#gid=411990024) (private) に改善案を追加しました。

マイルストーンの都合上，
- フィルタへの対処は行わないようにするためEL groupを切り分ける

および，上記で発覚した
- SSのEHを修正する

のみ変更し，現状の問題点の解決に留め大幅な変更はしていません。

ご確認いただけますでしょうか。
この方針でよろしければ，こちらで実装を進めようと思います。

**Comment by seki-hiro** [comment]
@conjikidow 現状特に問題になっているのは、挙げてくれた2点だと思うので、大幅な変更はせずそれだけに対処するという方針は良いと思いました。

一方で、切り出すのはNOISEではなく、対処を行うCRCの方だと思います。例えば、STIM210では、同一のgroup, local, highに`CRC_ERROR`と`STATUS_ERROR`と`NOISE_REMOVED`の3つが存在していると思うけど、この中の`NOISE_REMOVED`だけを切り出しても、正常（に見える）時にも割と起きている`STATUS_ERROR`によってCRC EHが発火してしまう状況は改善されないと思う。

あと細かいけど認識もれあるといけないからコメントすると、ELのシートのB列にEHの対処を書いてしまっているので、EHのシートの実態と合致していないと思う。例えば、テレメエラーの中でも、RM3100は多段でAOBC<->EXTの切り替えを行なったり、STIM210は多段でMPU9250に切り替える実装になっているので、注意が必要です。

**Comment by conjikidow** [comment]
@seki-hiro ありがとうございます。
`STATUS_ERROR` についても対処はしないほうがよいという認識がありませんでした。SSについてもchecksum error側を切り出す方向にしようと思います。

誤解を招いてしまい恐縮ですが，ELのB列は大まかな対処方針を記載しただけで，詳細はEHのシートに記載しています（RMの切り替えも反映しています）。

**Comment by seki-hiro** [comment]
はい、STIM, SSに限らず、全てnoiseではなくchecksum, CRC側を切り出すのがいいと思います。

詳細はEHの方ということで了解です。

**Comment by conjikidow** [comment]
その方針でスプシを修正しました。

今回「特に対処しない」ことにした，当初の「その他のエラー」のうち，切り出したCRC，checksum，xxhash以外に RW の `RW0003_EL_NOTE_TORQUE_CMD` がありました。こちらも特に対処しない方針でよろしいでしょうか。

```cpp
void APP_RW_CONTROLLER_exec_(void)
{
  float torque_rw_Nm[RW0003_IDX_MAX];
  // TODO_L: 4つ以上のRWを搭載することになったら4つ以上のRWに対応できるようにする
  MATRIX33_multiply_matrix_vector(torque_rw_Nm, aocs_manager->rw_distribution_matrix,
                                aocs_manager->internal_torque_target_body_Nm);
  VECTOR3_scalar_product(torque_rw_Nm, -1.0f, torque_rw_Nm); // RW司令は逆方向

  for (int idx_rw = 0; idx_rw < RW0003_IDX_MAX; idx_rw++)
  {
    AOCS_ERROR ret = DI_RW0003_set_torque_Nm((RW0003_IDX)idx_rw, torque_rw_Nm[idx_rw]);  // 実機確認で問題ないことを確認したが要注意
    if (ret != AOCS_ERROR_OK)
    {
      EL_GROUP el_group_error = (EL_GROUP)(EL_GROUP_ERROR_RW0003X + idx_rw);
      EL_record_event(el_group_error, (uint32_t)idx_rw, EL_ERROR_LEVEL_LOW, (uint32_t)RW0003_EL_NOTE_TORQUE_CMD);
    }
  }
}
```

**Comment by seki-hiro** [comment]
はい、元々lowという扱いになっていますし、テレコマラインに問題があったらテレメ読み出しの方でEHが発火すると思うので、ここで二重にEHを構えなくていいのではないかと思います。

**Comment by conjikidow** [comment]
了解です，ありがとうございます。

**Comment by conjikidow** [comment]
具体的な実装は別issueとして切り出しました。 #291 
方針が決まったため，こちらは close したいと思いますが，いかがでしょうか。
今後再整理の必要が出た場合は reopen するかあらためて issue を立てるのでよいかと思っています。

**Comment by seki-hiro** [comment]
closeでいいと思います！
