### ISSUE TITLE
RWステータス取得コマンドのコメントを外し、ステータスチェックELを実装する

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#265]
## 詳細
[RWステータス取得コマンド](https://github.com/ut-issl/c2a-aobc/blob/a609c54ac884998d055ef297cd37433aa0566f6d/database/CMD_DB/AOBC_CMD_DB_CMD_DB.csv#L199)はこちら。コメントアウトを外せば良い。  
ELのためにチェックするのは、[fault_state](https://github.com/ut-issl/c2a-aobc/blob/a609c54ac884998d055ef297cd37433aa0566f6d/src/src_user/Drivers/Aocs/rw0003.h#L39)

## close条件
実装して、試験したら。

## 備考
NA

**Comment by seki-hiro** [comment]
温度テレメと交互に呼んでも良い
