### ISSUE TITLE
Pytestが実行できる体制を整える

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#28]
## 概要
Pytestが実行できる体制を整える

## 詳細
Pytestが実行できる体制を整える

## close条件

- [x] Pytestを実装していく
- [ ] CIに組み込む

## 備考
NA

## 注意
NA

**Comment by 200km** [comment]
pytestに必要なC2A側の機能

https://github.com/ut-issl/c2a-aobc/pull/76#issuecomment-1643671802

**Comment by 200km** [comment]
@chutaro c2a-aobcでもGitHub Actionsでpytestを回したいのですが、参考になるものがあれば教えてもらえると嬉しいです。

**Comment by chutaro** [comment]
- 概要
  - https://github.com/ut-issl/c2a-core/tree/develop/Examples/minimum_user/src/src_user/Test の readme
  - ざっくりと言うと、こんな感じだと思います。
    - Test フォルダ配下に test を python で作成し、
    - 下記の必要ツールをインストールし、
    - c2a と wings を通信させた状態で、pytest コマンドを打って実行する
- 必要なツール
  - https://github.com/ut-issl/python-wings-interface
  - https://github.com/ut-issl/c2a-enum-loader

一方で、AEさん側で、wingsを使わずにc2aを実行し、pytestも実行するツール群を作成している気がしており、c2a-aobcが今後もAEさんと連携を密にする場合、AEの枠組みに乗った方が便利かつやりやすいのではないかという気もします。（いちおうメンションしておきます @sksat ）

**Comment by 200km** [comment]
ありがとうございます！

**Comment by 200km** [comment]
@chutaro これ、現状は手元で回していて、GitHubActions上ではまだ回していない感じですかね？参考になるyamlファイル見てみたいです。

**Comment by chutaro** [comment]
wingsを動かすのが大変そうなので、self hosted で CI サーバー上でやるしかないかなと思っていて、ただまだ手を付けていない状態です。github 移行後は pytest 無しで進めています。

**Comment by 200km** [comment]
> wingsを動かすのが大変そうなので

そういう感じなんですね。。。わかりました。  
`AEさん側で、wingsを使わずにc2aを実行し、pytestも実行するツール群を作成している気がしており`あたりが導入されたらGitHub Actionsでも動かせる感じですかね？

**Comment by chutaro** [comment]
- wings を動かす場合は self hosted で研究室サーバー上で動かすのが楽だと思っています（comポートの通信とかが大変そう）
- AEさんのツールが github actions で動かせるかは AE さんに聞きたいですね。まだAE側でも整備段階だと思うので、アップデートあったら共有します。

**Comment by 200km** [comment]
使おうとしてつまづいたところ

## c2a-enum-loader
- 次の部分でenumが読めず、エラーが出ている
  https://github.com/ut-issl/c2a-aobc/blob/605722a5d9ea252c3f9ec40d30bbd62c9a13e4d0/src/src_user/Drivers/Aocs/oem7600.h#L45
  - 右辺で`OEM7600_TLM_ID_RANGE`を使っているのが悪く、直接`0x0000102B`と書けばエラーは出ない
- 同様のエラーとして、`ValueError: invalid literal for int() with base 10: XXH_rotl32`が出るが、これはどの部分か不明。外部ライブラリであるxxHashに関連しているのはわかるが、`XXH_rotl32`はenumで使われていないので謎

**Comment by 200km** [comment]
> ValueError: invalid literal for int() with base 10: XXH_rotl32

については、`xxHash.c`内で一行でenum定義されていたものを複数行に変えると解消された。XXH_rotl32は関係なかったのでエラー表示は謎ではある。

xxHashは外部ライブラリから引っ張ってきたものなので、coding ruleを適応させたくはない。enum loaderからファイル指定で除外できると嬉しい。

**Comment by 200km** [comment]
#150 のとおり、上のエラーを除去した状況ではpytestが実行できるようになった。ただし、次の部分でつまづいた。

- `Cmd_APP_AOCS_MANAGER_SET_REFERENCE_TIME`コマンドをpytestしようとしたら、引数の方部分でエラーが出た。

このコマンドはdouble型を引数に持っているので、その部分でエラーが出たのではないかと思う。

**Comment by 200km** [comment]
> Cmd_APP_AOCS_MANAGER_SET_REFERENCE_TIMEコマンドをpytestしようとしたら、引数の方部分でエラーが出た。

これはdouble型関係なく、引数が一つであることが問題っぽい。次のようにするとエラー回避できたが、これが想定仕様なのかは微妙な気もする。

https://github.com/ut-issl/c2a-aobc/blob/138fce8df5e26a026436b050d2234837954e685f/src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/test_aocs_manager.py#L43

**Comment by 200km** [comment]
c2a-coreの方を見ても、引数ひとつの時は同じような書き方をしているようなのでそういう仕様ということなのかもしれない。ただ分かりづらく、どこにも記述がないので初めての人はハマってしまいやすそうな気がする。

https://github.com/ut-issl/c2a-core/blob/a7b384cc91be5ebaeb8d6ea52503037033c6b0aa/Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py#L119

@chutaro 引数一つの時のこの現象についてコメントいただけると嬉しいです。

**Comment by chutaro** [comment]
> 引数一つの時のこの現象

これはシンプルに python で tuple を使うときの文法の話だと思います
参考：https://note.nkmk.me/python-tuple-single-empty/

**Comment by chutaro** [comment]
enum の足し算表記と、一行表記は enum loader の方では想定していなそうです。短期的には c2a のソースコードを修正することで対応していただけるとありがたいです！

**Comment by 200km** [comment]
>  python で tuple を使うときの文法の話

ありがとうございます。pythonでは常識的な話という感じなんですかね。  
AOCS向けにマニュアル作るときには注釈つけようと思います。

これとは別に、pytestで使う関数全体的にコメントが欲しいなとは思いました。今はコード全部読むか、他のコードを真似て書くしかない感じで少し面倒にかんじました。

> 短期的には c2a のソースコードを修正する

足し算表記は対応しました。https://github.com/ut-issl/c2a-aobc/pull/153  
一行表記の方は外部からとってきたもので、ソースコードを修正するのはしたくなく除外ファイルとして扱いたいということで、issueを出させてもらっています。https://github.com/ut-issl/c2a-enum-loader/issues/23
