### ISSUE TITLE
initialモードのリファクタ

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#31]
## 概要
initialモードのリファクタ

## 詳細
Initialモードのタスクリストにアプリが登録されていることに起因して幾つかの不都合が発生している．Initialモードは地上試験のために存在しているが，その取り扱いを再考する．
- 地上試験のためのモードに軌道上で入る意味はない
- MTQが出力している状態で他のモードからInitialモードに遷移すると，MTQが出力されたままになってしまう
- 試験を行うためにアプリがたくさん呼ばれており，3-3アノマリが出やすくなっている
  - これ自体は大きな問題ではない
- （セットで呼ばれる想定のMTQのPWM制御と消磁制御のアプリが片方しか呼ばれていない）
  - これはまずアプリ側で対応

## close条件
リファクタしたら

## 備考
NA

## 注意
NA

**Comment by seki-hiro** [comment]
対応方針、賛成です。

> 打ち上げ後、他モードからinitialモードに遷移するのは想定していない

Bdotで角速度が増加してしまう場合に、Initialモードに遷移する場合があると思います。

> initialタスクリストの中身を他のモード（特に全てのコンポを呼び出しているfine_three_axis）と近い形式にする。

コンポの呼び出し頻度を実際に使われるモードに揃えておくことで、EHの検証とかも行いやすくなると思うので、この方針が良さそうです。

**Comment by 200km** [comment]
> Bdotで角速度が増加してしまう場合に、Initialモードに遷移する場合があると思います。

確かにアノマリーケースではありましたね。いずれにせよ上に書いた対応方針で包含されるのでこのまま進めようと思います。
