### ISSUE TITLE
Driver受信バッファサイズを調整する

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#39]
## 概要
Driver受信バッファサイズを調整する

## 詳細
c2a-coreアップデートにより、Driver受信バッファサイズを細かく設定できるようになった。  
メモリの余裕を生むため、INAなどテレメ量が小さなものは小さなサイズ割当するのがよい

## close条件
調整したら

## 備考
NA

## 注意
NA

**Comment by chutaro** [comment]
仕様とかまとめてこのissueに書きました：https://github.com/ut-issl/c2a-mobc-onglaisat/issues/69

**Comment by seki-hiro** [comment]
STTはバッファサイズを大きくしたい。
https://github.com/ut-issl/c2a-aobc/pull/137#issuecomment-1650998837

**Comment by seki-hiro** [comment]
@conjikidow @chutaro これ今どんな感じでしょうか？8/7までに、できればSTTのバッファサイズを大きくしたいと思っています。

**Comment by chutaro** [comment]
必要な情報は出したと思っているので @conjikidow の方で進めてくれると助かります！質問はウェルカムだしレビューもします。

このまえDriver読みながらまとめたメモも貼っておきます：https://docs.google.com/document/d/1MlhWrqn__GfDuqCtRMgsLJ0q0d6tpNiVz7QrBjGEIi0/edit?usp=sharing

**Comment by seki-hiro** [comment]
サポートありがとうございます！
@conjikidow 何か困ってる点あれば教えてください！

**Comment by conjikidow** [comment]
すみません，今確認しました。
手が回っていないだけなので，急いで進めます，すみません。

**Comment by 200km** [comment]
@conjikidow `各コンポのテレメサイズ確認方法`について、ローカルミーティングで伝えたけど、一応ここにも書いておきます。

- c2a-aobcのコードを見る方法
  - 各ドライバコードに[RX_FRAME_SIZE](https://github.com/ut-issl/c2a-aobc/blob/605722a5d9ea252c3f9ec40d30bbd62c9a13e4d0/src/src_user/Drivers/Aocs/mpu9250.c#L15)的なものが定義されているので参考になる
- s2e-aobcのコードを見る方法
  - s2eのコンポ模擬側にも[TlmSize](https://github.com/ut-issl/s2e-aobc/blob/7abbabc2447855fc9f83387c93e677e194da996f/src/component/aocs/mpu9250_gyro.cpp#L32)の情報が書かれている
- 仕様書を見る方法

**Comment by conjikidow** [comment]
@200km (@seki-hiro @chutaro)
バッファサイズは [driver_buffer_define.h](https://github.com/ut-issl/c2a-aobc/blob/develop/src/src_user/Settings/DriverSuper/driver_buffer_define.h) で定義するようになっていますが，その値は示していただいたように [mpu9250.c](https://github.com/ut-issl/c2a-aobc/blob/605722a5d9ea252c3f9ec40d30bbd62c9a13e4d0/src/src_user/Drivers/Aocs/mpu9250.c#L15) などをもとに設定することになると思います。

参照元が（ヘッダーでなく）ソースにあることから，どのようにするのが良いかご意見を伺いたいです。
例えばそのままの枠組みで実装しようとすると driver_buffer_define.h で mpu9250.c をincludeしなければならず，またその driver_buffer_define.h を再び mpu9250.c（あるいは mpu9250.h） でincludeすることになり，不可能です。

以下のような案が考えられるかと思います。
- driver_buffer_define.h で直接値を設定する
  - mpu9250.c は参照しないため，バグのもととなりうる
  - 一方を変える場合，もう一方も変える必要がある
- mpu9250.c などにあるデータ長のマクロ定義をヘッダー（mpu9250.h）などに移す
  - そのヘッダーを driver_buffer_define.h でincludeし，driver_buffer_define.h を mpu9250.c でincludeする
- バッファサイズ定義を mpu9250.c で行う
  - mpu9250.c 内でデータ長からバッファサイズを設定するため，mpu9250.c で完結する
  - 既存の driver_buffer_define.h で設定するという枠組みから外れる

**Comment by chutaro** [comment]
driver_buffer_define.h でバッファサイズを定義したいけど、その定義に mpu9250.c で定義されている define値やenum値を使いたい、という感じですかね？

**Comment by 200km** [comment]
@conjikidow @chutaro 

> バッファサイズは [driver_buffer_define.h](https://github.com/ut-issl/c2a-aobc/blob/develop/src/src_user/Settings/DriverSuper/driver_buffer_define.h) で定義するようになっています

というのはC2Aとしてのcoding ruleでそう決まっている感じですか？  
ここではdefault値だけ設定していて、コンポ毎の細かな値はコンポに限定された狭い範囲で定義するのが自然な気もしました。

例えば、`di_mpu9250.c`で直接`DS_STREAM_REC_BUFFER_SIZE_MPU`で定義して、`static uint8_t DI_MPU9250_rx_buffer_allocation_[DS_STREAM_REC_BUFFER_SIZE_MPU];`　とするのでも良いのでは？という感じです。

バッファサイズをmpu9250.c で定義されているdefine値で設定するべきかはまた別で議論したい気はします。バッファサイズとFRAME_SIZEが一対一対応なのかという議論があると思いますので。

**Comment by chutaro** [comment]
slackでも書きましたが、 mpu9250.h にバッファサイズを定義するのが良いと思います。

**Comment by 200km** [comment]
ありがとうございます。 `バッファサイズはdriver_buffer_define.hで定義する`というルールがあるわけではないということで理解しました。議論の的をコンポ個別のDriverとDIに限定できるということだと思います。

**Comment by 200km** [comment]
`mpu9250.h, c`か`di_mpu9250.h, c`のどこで定義するのかという場所の問題と、すでにあるFRAME_SIZE定義と同じ値にすべきなのかという値の関連性の問題は引き続き議論が必要なのかなと思います。

**Comment by conjikidow** [comment]
ありがとうございます。
driver_buffer_define.h でなくコンポごとの場所で定義する方針としたいと思います。

一方で

> mpu9250.h, cかdi_mpu9250.h, cのどこで定義するのかという場所の問題と、すでにあるFRAME_SIZE定義と同じ値にすべきなのかという値の関連性の問題は引き続き議論が必要なのかなと思います

についてはどのようにするのが良いか，考えはありますでしょうか。

**Comment by 200km** [comment]
slackでの議論をまとめます。
バッファサイズについては次の三種類がある。
- 大きなテレメのデフォルト値 : 128, 256などのキリの良い値
- 小さなテレメのデフォルト値: 16, 32などのキリの良い値
- 上の二つに当てはまらず、より細かく最適設定したい値

このうち、上の二つは`driver_buffer_define.h`で定義するのが自然。  

`上の二つに当てはまらず、より細かく最適設定したい値`は今回の場合はSTTやGPSになると思いますが、それらは`compo_name.h, c`か`di_compo_name.h, c`のどこで定義するのが良いと思います。

**Comment by 200km** [comment]
compo_name.h, cかdi_compo_name.h, cのどこで定義するのが良いか？というのは次の二つのどっちかですかね。

- `compo_name.h`で一つだけ値を定義し、両方のcの中でそれを参照する
- `compo_name.c`でFRAME_SIZEを定義し、それとは独立で`di_compo_name.c`でバッファサイズを定義

前者は二つの値が同じ値になることや、リンクしているという前提のもので、後者は二つの値が必ずしもリンクしなくて良いと考えているものだと思います。

前者は`バッファサイズ = FRAME_SIZE`か`バッファサイズ = FRAME_SIZE + hoge`みたいな使い方だと思います。  
後者はバッファサイズをFRAME_SIZEに一番近い切りの良い値にするみたいな使い方が綺麗な気がしています。  

個人的には後者かなと思いますが、強い意見ではなくどちらでも良いかなとは思います。

**Comment by conjikidow** [comment]
まとめ，コメントありがとうございます。

STTやGPSの場合，UARTで非同期通信のため，ds_stream のバッファサイズは if_rx の2倍とするのが良いとのことです。
したがってミスを減らすためには値をリンクさせる（すなわち前者）のが良いのかなと思います。

**Comment by 200km** [comment]
> ds_stream のバッファサイズは if_rx の2倍とするのが良い

if_rxというのは下記の値ですよね。

https://github.com/ut-issl/c2a-aobc/blob/605722a5d9ea252c3f9ec40d30bbd62c9a13e4d0/src/src_user/Settings/DriverSuper/driver_super_params.h#L15C9-L15C36

そもそもこの値を何に設定するかという議論もある気がしますし、`if_rx の2倍とするのが良い`というのがAOBCが今やりたいことにも当てはまるのかという議論ふたつある気はしますね。

> そもそもこの値を何に設定するか

今の１４４は必要最小限という部分に焦点を当てて決めたものです。[ここ](https://github.com/ut-issl/c2a-mobc-onglaisat/issues/69)での議論の前提になっている`H/Wから決める`というものではないです。前提が違うので、その後の`if_rx の2倍とするのが良い`が本当に当てはまるのかも考える必要があると思います。

> AOBCが今やりたいこと

一般的に、
- ミスを減らすためには値をリンクさせる
- 自由に設定できるように別々の値にする

がコンフリクトすることは多いですが、今回の場合は`if_rx の2倍`というのがどこまで絶対的なものなのかによる気がします。ただの目安なら、その他の観点も考えて個別設定する可能性があるべきだと思います。

特にSTTが今回やりたいのは、今までよりも倍くらいのテレメトリを扱いたいという極端なものなので、STTに合わせて全てのUARTを大きなサイズに設定するのではなく、他のUARTとSTTとを別で扱うべきという考えが良いと思います。

**Comment by conjikidow** [comment]
その値はデフォルト値ですが，ここで想定しているのはSTT，GPSRそれぞれ固有のif_rxです。

**Comment by 200km** [comment]
slackで例として示してくれたprivateレポジトリのOBCは、`if_rx`は変更せず、`driver_buffer_define.h`で定義している`DS_STREAM_REC_BUFFER_SIZE`のみを個別に設定していたので、その議論をしているのかと思いました。  

質問の最初に書かれている `バッファサイズはdriver_buffer_define.hで定義するようになっています`についても、ここで定義されているのは`if_rx`ではなく`DS_STREAM_REC_BUFFER_SIZE`の方なので、なんか話が噛み合っていない気がします。。。

**Comment by conjikidow** [comment]
その例でも 'DSC_set_rx_buffer_size_in_if_rx' によって if_rx も変更していると思っているのですが違うのでしょうか？
if_rx <= ds_stream である必要があるため，ds_stream を小さくした場合 if_rx も削減する必要があると思っています。

**Comment by conjikidow** [comment]
> 質問の最初に書かれている バッファサイズはdriver_buffer_define.hで定義するようになっていますについても、ここで定義されているのはif_rxではなくDS_STREAM_REC_BUFFER_SIZEの方なので

確かにそうですが，if_rx <= ds_stream および ds_stream=if_rx*(1|2) から ds_stream の値も if_rx に依存するのが自然だと考えていました。

**Comment by 200km** [comment]
何となくわかってきました。

`if_rx`が、`DSC_set_rx_buffer_size_in_if_rx`にあるような設定された後のことを指しているんですね。僕は上で書いたように`DS_IF_RX_BUFFER_SIZE`などの全体に対する設定値の話を考えていました。つまり、`DS_IF_RX_BUFFER_SIZE_GPS`みたいなのを同じ場所に定義したいという話かなと。（それはファイルの構成上綺麗でないので反対していた）  
例で実装されているのは、（if_rx１倍のケースですが）`DSC_set_rx_buffer_size_in_if_rx(DS_IF_RX_BUFFER_SIZE)`という感じなので、`DS_IF_RX_BUFFER_SIZE_HOGE`を増やすということではないですよね。

整理すると、`Settings/DriverSuper`内で定義される値は、
- `DS_IF_RX_BUFFER_SIZE`は何かしらデフォルト値を一つ決め、UART通信でテレメサイズが大きめなものについてはこのデフォルトはこれを使う
- `DS_STREAM_REC_BUFFER_SIZE`は上で書いたように大小二種類くらい定めて、一つは`DS_IF_RX_BUFFER_SIZE`とリンクさせて２倍にするが、もう一つは適当に値を決める（例で示されているのと同じ）

という感じですかね。

これを各コンポでどう使うかという部分では、
1. 比較的テレメサイズの大きなコンポ（STIM, MOBCなど）は`DS_STREAM_REC_BUFFER_SIZE`の大きい方を使う
   - GPS-RとSTTがこれに含まれるかは、`DS_IF_RX_BUFFER_SIZE`がどの値に設定されるかによる
2. 比較的テレメサイズの小さなコンポ（I2C系）は`DS_STREAM_REC_BUFFER_SIZE`の小さい方を使う
3. テレメサイズが`DS_STREAM_REC_BUFFER_SIZE`の大きい方で足りない場合は、個別のコンポで設定する
   - これは、コンポの`FRAME_SIZE`から必要最小限の値（`if_rxサイズ`も`ds_streamサイズ`もどちらも）を設定するということになる
   - 関係式としては、`2 * if_rxサイズ = ds_streamサイズ >= FRAME_SIZE`

で、三つ目のパターンでどこで値を定義すべきかという話に戻りますが、
a. FRAME_SIZEだけ定義して、あとは計算式でif_rxサイズとds_streamサイズを決めるか
b. FRAME_SIZEとds_streamサイズを別々で定義して、`2 * if_rxサイズ = ds_streamサイズ`でif_rxサイズだけ計算で出す
c. 三つ全てバラバラで定義する

の三パターンになるという感じですかね。

**Comment by 200km** [comment]
@conjikidow 君的にはミスを減らすために、aのパターンが良いということですよね。  

ただ、1,2のコンポについては、コンポ毎の`FRAME_SIZE`と`DS_STREAM_REC_BUFFER_SIZE`の間の関係が要件を満たしているかは人力確認になるので、３のケースだけそこにこだわってもなという違和感もあります。  
1,2のコンポは、現状はif_rxサイズとds_streamサイズだけ数式でリンクしている状態（bの状態）なので、3もbと同じような構成にしておけば、全てのパターンで考えるべき要素の数やレイヤーが揃って、理解しやすかったり修正しやすいというのもある気がします。

とはいえ、前にも書いた通り強い意見ではなくどちらでも良いかなとは思います。


あとは、そもそも`DS_IF_RX_BUFFER_SIZEがどの値に設定されるか`という部分で、十分に大きな値を設定したら３のコンポがなくなるので、ここでの議論はあまり意味はなくなるかもしれませんね。

**Comment by conjikidow** [comment]
ミーティングを行い，ひとまず以下の方針となりました。

- I2Cのコンポはまとめて扱う
  - 適切な `DS_STREAM_REC_BUFFER_SIZE` を driver_buffer_define.h で定義する
  - その値を `compo_name.c` ，`di_compo_name.c` で参照する
    - I2Cは同期通信なので if_rx と ds_stream は同じでよい
- UARTのコンポは一旦保留しデフォルト値とする
  - デフォルト値をどうするかは要検討
  - STTの要求から現状の144byteよりも大きくしたいがどうするのがよいか確認する
    - 例えば256byteや512byteとするか，ハードの制約である1024byteとするか
    - `DS_IF_RX_BUFFER_SIZE` や `DS_STREAM_REC_BUFFER_SIZE_DEFAULT` が他の箇所のどのように影響するか

この上でメモリ使用量がどうなるかを確認し，その結果次第でUARTのコンポ（STIM210など）についても個別に減らすことを考えます。

**Comment by conjikidow** [comment]
#161 をmergeしました。

まだ実機で確認できていないところもあるためcloseは保留し，#159 でのSTTの試験などで動作確認できてからcloseしたいと思います。

**Comment by conjikidow** [comment]
#170 でSTTのテレメが受信できることは確認できました．
一方でリアルスカイ試験でSTTのテレメのescapeが頻発することが発覚したため，STTのバッファサイズを増やす必要がありそうです．

**Comment by conjikidow** [comment]
@.seki-hiro さんとlocalで話して，10~20byteほど増やすことになりましたので，その方針でPR出します。

**Comment by conjikidow** [comment]
#200 をmergeしたのでこちらcloseします。
