### ISSUE TITLE
ユリウス日定義の明確化と変更

### ISSUE THREAD

**Issue by 200km** [ut-issl/c2a-aobc#53]
## 概要
ユリウス日定義の明確化と変更

## 詳細
搭載S/Wで使われているユリウス日のうるう秒の扱いについて定義を明確化にして変更する。  
地上側でケアして運用すれば問題ないが、どの定義にしたほうが運用が楽になるかを考えて修正する。

## close条件
修正したら

## 備考
NA

## 注意
NA

**Comment by t-hosonuma** [comment]
こちらについては，この[PR](https://github.com/ut-issl/c2a-aobc/pull/79)にて，地上側に合わせてうるう秒を考慮した形でJday算出する方式に変更した．
