### ISSUE TITLE
コマンド数の最大値を増やすべきかどうか議論する

### ISSUE THREAD

**Issue by suzuki-toshihir0** [ut-issl/c2a-aobc#65]
## 概要
AOBCに定義できるコマンド数を255個から拡張すべきかどうか考えたい．

## 詳細
現状C2A-AOBCには234個のコマンドが定義されているが，coreで10個単位でコマンドが増えそうという話も出ており，コマンド数上限を増やせないか考えたい．コマンド数が増えていく要素は以下があると思われる．

- core updateによるコマンド数増加
  - C2A AOBCにおけるコマンド数増加は避けられない
- AOBCへの機能追加によるコマンド数増加
  - C2A AOBCへのコマンド数数増加は避けられない
- 第0世代と第1世代をまとめて扱うことによるコマンド数増加
  - モジュールによってどのコマンドを定義するかについて，cmd dbで調整すれば著しくコマンドが増えることはなさそう

## close条件
- [ ] コマンド数上限を増やすかどうか考えたら

## 備考
なにかあれば

## 注意
- 関連する Projects が存在する場合，それの紐付けを行うこと
- 可能ならば `priority` ラベルを付けること
- 可能ならば Assignees を設定すること
- close するときは結論を明記すること

**Comment by suzuki-toshihir0** [comment]
（こちらも遅くなってしまっていてすみません）このissueもやるだけだと思いますが、何個までコマンド最大数を増やしたいかはちょっと考えたいですね。増やしてみてどこまで影響があるのかを見るのが先かもしれませんが。

**Comment by suzuki-toshihir0** [comment]
ベースとなるcommit hash
https://github.com/ut-issl/c2a-aobc/commit/94a5afc5bef77adf8b1baba91465cdb714050456

もともとのサイズ
Program size: 434,657 bytes (used 84% of a 520,192 byte maximum) (185.87 secs)
Minimum Memory Usage: 118224 bytes (90% of a 131072 byte maximum)

ここからcommand analyze paramsを変化させていく。

// 1テレメトリパケット(=1ページ)に格納されるコマンド数
#define CA_TLM_PAGE_SIZE (16)
// コマンドテーブルページ数
#define CA_TLM_PAGE_MAX (16)
// コマンドテーブルサイズ
#define CA_MAX_CMDS (CA_TLM_PAGE_SIZE * CA_TLM_PAGE_MAX)

コマンドテーブルのページ数を変えていく。

CA_TLM_PAGE_MAX = 17の場合
Program size: 434,657 bytes (used 84% of a 520,192 byte maximum) (55.23 secs)
Minimum Memory Usage: 118480 bytes (90% of a 131072 byte maximum)

CA_TLM_PAGE_MAX = 18の場合
Program size: 434,657 bytes (used 84% of a 520,192 byte maximum) (54.94 secs)
Minimum Memory Usage: 118736 bytes (91% of a 131072 byte maximum)

CA_TLM_PAGE_MAX = 19の場合
Program size: 434,657 bytes (used 84% of a 520,192 byte maximum) (53.25 secs)
Minimum Memory Usage: 118992 bytes (91% of a 131072 byte maximum)


CA_TLM_PAGE_MAXを1増加させる、つまりコマンドを16個増やすと256byte増える。コマンド1個あたりの増分は16byte。

**Comment by suzuki-toshihir0** [comment]
- 現状のメモリのあまりは 131072 - 18224 = 12848 byte。
- コマンド1個あたりメモリが16byte食われるので、最大で 12848 byte / 16 = 803 個　（ページ数換算で50ページ程度）まで許容できる。
- 今後増えるコマンド数はなんともいえないが、core updateでコマンドが増えたりすることもありえるため、2ページ増やして32個増やすくらいがリーズナブルにも見える。

**Comment by suzuki-toshihir0** [comment]
@200km コマンド数ですが、コマンドテーブルのページ数を増やしていった時の挙動は上に書いているとおりになりそうです。今の段階で今後コマンドが何個増えるか正確に見積もることは難しいとは思いますが、2ページ（つまりコマンド数でいうと32個）増やすくらいであれば、メモリインパクトは 512[byte] / 131072[byte] = 0.4% 程度に収まりそうで妥当かなと思います。いかがでしょうか？

**Comment by 200km** [comment]
検討ありがとうございます。ひとまず32個増やすと言うことで進めて良いと思います。

**Comment by suzuki-toshihir0** [comment]
わかりました、ではひとまず32個でPR出しちゃいますね。
