### ISSUE TITLE
Example内のCMakeLists.txtを整理する．

### ISSUE THREAD

**Issue by suzuki-toshihir0** [ut-issl/c2a-aobc#66]
## 概要
Example内のCMakeLists.txtを整理する．

## 詳細
どこまで `c2a-aobc` のCMakeListsで面倒を見るべきで，どこから `c2a-aobc-example` のCMakeLists.txtで面倒を見るべきなのか整理したい．現状その設定がかぶってしまっている．

## close条件
整理してCMakeLists.txtを改修したら

## 備考
なにかあれば

## 注意
- 関連する Projects が存在する場合，それの紐付けを行うこと
- 可能ならば `priority` ラベルを付けること
- 可能ならば Assignees を設定すること
- close するときは結論を明記すること

**Comment by 200km** [comment]
Exampleディレクトリがなくなったので、一旦削除する。

**Comment by 200km** [comment]
こちらに移動
https://github.com/ut-issl/c2a-aobc-example/issues/6
