### ISSUE TITLE
古い generate tlm を新しいものに置換する

### ISSUE THREAD

**Issue by chutaro** [ut-issl/c2a-aobc#69]
## 概要
古い generate tlm を新しいものに置換する

## 詳細
関連 PR
- https://github.com/ut-issl/c2a-core/pull/584

## close条件
全て置換したら

## 備考
なにかあれば

## 注意
- close するときは結論を明記すること

**Comment by seki-hiro** [comment]
@chutaro このPRで対応するべきは、以下の2点でしょうか？
- database配下opsファイルのGENERATE_TLMを新しいものに書き換える
- nbc_start_hk_tlm.cの定期テレメに関するGENERATE_TLMを新しいものに書き換える

**Comment by chutaro** [comment]
これですが，本質的ではない & 僕がやった方が早い気がするので明日あたりにPR出します

**Comment by seki-hiro** [comment]
ありがとうございます！

**Comment by chutaro** [comment]
opsファイルは AOBCの単体試験用という認識でいいですかね？

**Comment by seki-hiro** [comment]
このレポジトリのはおそらく全てそうです

**Comment by chutaro** [comment]
了解です．それならmobcを経由するケースなどを考えなくて良さそうなので一斉置換したいと思います

**Comment by chutaro** [comment]
終わったのでクローズ
