### ISSUE TITLE
テレメエラーのFDIRを見直す

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/c2a-aobc#75]
## 概要
テレメエラーのFDIRを見直す

## 詳細
従来の電源リセットだと改善していないコンポーネントがある。DIのリセットが有効な場合がある。

## close条件
テレメエラーのFDIRが更新されたら

## 備考
NA

## 注意
NA

**Comment by conjikidow** [comment]
方針について別の場所でCDHと相談中。
issueとしてはこのまま残しておき，次のマイルストーンまでに方針を具体化して対応する。

**Comment by conjikidow** [comment]
#300 で対応したため close
